version: "3"

volumes:
  kafka-logs:
  kraft-combined-logs:

services:
  kafka:
    container_name: kafka-server
    build:
      args:
        KAFKA_CLUSTER_ID: ${KAFKA_CLUSTER_ID}
        NODE_ID: ${NODE_ID}
        KAFKA_VERSION: ${KAFKA_VERSION}
        SCALA_VERSION: ${SCALA_VERSION}
      dockerfile: Dockerfile
    volumes:
      - type: volume
        source: kafka-logs
        target: /tmp/kafka-logs
      - type: volume
        source: kraft-combined-logs
        target: /tmp/kraft-combined-logs
    ports:
      - "9092:9092"
      - "9093:9093"
    restart: unless-stopped